# Spring properties
spring:
  application:
     name: message-generation  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  cloud:
   services:
      registrationMethod: route

management:
  context-path: /admin
  security:
    enabled: false

# HTTP Server
server:
  port: 8084   # HTTP (Tomcat) port

producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false

logging:
  level:
    org.springframework.security: debug