# Spring properties
spring:
  application:
     name: message-generation  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  cloud:
   services:
      registrationMethod: route

management:
  context-path: /admin
  security:
    enabled: false

# HTTP Server
server:
  port: 8084   # HTTP (Tomcat) port

producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false

# Discovery Server Access
#  1. DEV ONLY: Reduce the lease renewal interval to speed up registration
#  2. Define URL of registration server (defaultZone)
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
logging:
  level: debug

